### ISSUE TITLE
Any chance you will be able to do full text diffs with Sketch 43's new file format?

### ISSUE THREAD

**Issue by drasnop** [mathieudutour/git-sketch-plugin#100]
Maybe by unzipping and rezipping the file before and after committing? e.g [this](http://stackoverflow.com/questions/8001663/can-git-treat-zip-files-as-directories-and-files-inside-the-zip-as-blobs). Automatic merges would be a real life changer for multi-people collaboration.

**Comment by mathieudutour** [comment]
working on it ;) (I [started](https://github.com/mathieudutour/git-sketch-plugin/pull/74) on this path before Sketch 43 but the new format makes everything way easier)

I agree that automatic merges would unlocked a lot of stuffs, but on the downside, I would need to remove visual diffs because they are not mergeable. So I'm thinking about a small mac app which would show the diffs between commits. 
What do you think?

**Comment by jasonkylefrank** [comment]
@mathieudutour When you say that you would need to remove the visual diffs, do you mean that the exported pngs would not be a part of the process anymore?  If that's the case, I would assume that we wouldn't have a way to visually see how artboards have changed over time on GitHub?

**Comment by mathieudutour** [comment]
not on github no. but there could be a companion app to do that

**Comment by drasnop** [comment]
I find the artboard visual diffs pretty convenient. Other members of the teams can just look at the repo and see what I'm working on, without having to clone it or install any app.

Would it be possible to keep the visual diffs for "normal" (non-merge) commits, and just have no visual diffs when you merge? Would that mess up the diffs just for one commit, or for all subsequent commits?

**Comment by mathieudutour** [comment]
Yes I understand, that's why I created this plugin in the first place ;)

But the issue with the visual diffs right is that you need to commit images in the git repo. So it completely goes against "automatic merges". You can't remove them from some commits only.

**Comment by mathieudutour** [comment]
Hi guys,

wanted to share my progress on that front: https://github.com/kactus-io/kactus/issues

I would really appreciate if you could test it :)

**Comment by mathieudutour** [comment]
and let's move the discussion there
