### ISSUE TITLE
Not working on Sketch 41.2 & up

### ISSUE THREAD

**Issue by guzforster** [mathieudutour/git-sketch-plugin#101]
When I double click the plugin or move it to the plugins folder, nothing happens, it doesn't install.

**Comment by mathieudutour** [comment]
https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/FAQ.md#i-installed-the-plugin-but-its-not-showing-in-the-sketch-plugin-menu ?

**Comment by guzforster** [comment]
Thank you, that solved it. Wouldn't it be better to put the latest release directly in the "download" button?

**Comment by mathieudutour** [comment]
it would. I think I fixed it twice already, not sure why it's still broken

**Comment by mathieudutour** [comment]
Actually, which "download" button are you talking about?

**Comment by guzforster** [comment]
The "Clone or download" button. That's usually where I go when I want to download a Sketch plugin.

**Comment by mathieudutour** [comment]
oh but I can't change that, it's the github button. if you look at the instruction on the readme, that's the right link
