### ISSUE TITLE
Sketch 43 (36781) Installation problems

### ISSUE THREAD

**Issue by FatEd11** [mathieudutour/git-sketch-plugin#102]
This plugin doesn't seem to install anymore. If sketch open it simply closes the open window, and then does nothing. Installing through toolbox or runner doesn't seem to solve the issue either.

Is this just a versioning thing?

**Comment by mathieudutour** [comment]
I just published 0.10.0. Can you check if it fixes your issue?

**Comment by FatEd11** [comment]
Doesn't seem to have 😢  

Admittedly I've updated my sketch recently to 43.1 (39012) so might have fixed for version I raised this ticket on...

**Comment by mathieudutour** [comment]
Hum. Can you tell me exactly what happens? Is the plugin showing in the menu?

**Comment by FatEd11** [comment]
Nope. So it seems to run the install, and the success message even shows. But it doesn't appear in the menu.

It also seems to close the open sketch window during install.

**Comment by mathieudutour** [comment]
you are downloading the plugin from the release page right?

**Comment by FatEd11** [comment]
Yep

**Comment by holyman1010** [comment]
me either, can't install the plugin, my sketch version: 43.1

**Comment by mathieudutour** [comment]
I just downloaded the new sketch beta 43.1 and it seems to work for me. Can you go to `Plugins > Manage plugins > the small gear > Show plugins folder` and send me the `Git.sketchplugin`?

**Comment by FatEd11** [comment]
Attached.

[Git.sketchplugin.zip](https://github.com/mathieudutour/git-sketch-plugin/files/912883/Git.sketchplugin.zip)

**Comment by mathieudutour** [comment]
hum I don't think it was downloaded from the releases page: https://github.com/mathieudutour/git-sketch-plugin/releases

**Comment by holyman1010** [comment]
After double-clicking the Git.sketchplugin, it didn't get into the plugins folder...

**Comment by FatEd11** [comment]
Apologies you are right. I thought you meant something different when you said the releases page.

**Comment by mathieudutour** [comment]
Cool.

@holyman1010 hum I don't what happened then, it might be a sketch bug. Anyway, you can drag and drop the plugin there manually, that's all "double-clicking on it" do

**Comment by holyman1010** [comment]
Hi, mathieudutour
I just solved it! THX!

**Comment by arteforme** [comment]
I'm having similar issues on version 43.2.  When double clicking the `.sketchplugin` file, it doesn't get copied over to the Plugins folder.  When I move the `.sketchplugin` file over to the Plugins folder, I don't see Git as a menu item under Plugins.  @holyman1010 what solved the issue for you?

**Comment by holyman1010** [comment]
I go to the release page to download the plugin, then it works!
https://github.com/mathieudutour/git-sketch-plugin/releases
I am not sure why cause this problem, but this links is work for me.

**Comment by arteforme** [comment]
Thanks, that worked for me.
