### ISSUE TITLE
Fail to init new repo

### ISSUE THREAD

**Issue by handaru** [mathieudutour/git-sketch-plugin#105]
### How did it happen?
1. Plugins -> Git -> Advanced -> Init git repo
2. Type any word to be new repo
3. Alway get Failed error popup

<img width="469" alt="uikits" src="https://cloud.githubusercontent.com/assets/1574087/24797686/87f42a8e-1bbc-11e7-8efc-cf0444ce4552.png">

<img width="449" alt="failed" src="https://cloud.githubusercontent.com/assets/1574087/24797685/87f2fbe6-1bbc-11e7-933c-a48b9c28e108.png">

**Comment by handaru** [comment]
Solved, problem in my git setting. Sorry.

**Comment by mathieudutour** [comment]
No worry
