### ISSUE TITLE
Cannot generate artboard diffs

### ISSUE THREAD

**Issue by jadar** [mathieudutour/git-sketch-plugin#106]
I can't seem to generate any artboard diffs. I select the option in the plugin and then check the directory for the files–they're not there. I'm using Sketch 42 and the latest release of the git plugin.

### How did it happen?
1. Create new Sketch file and artboard.
2. Init git repo
3. Use generate pretty diff button

### Error log
<img width="424" alt="screen shot 2017-04-07 at 12 16 37 pm" src="https://cloud.githubusercontent.com/assets/3793928/24811565/2d2695a4-1b8c-11e7-8d4d-6a0f99b68196.png">

**Comment by mathieudutour** [comment]
I just published 0.10.0 which fixes some bugs. Could you check if it's fixed? I haven't been able to reproduce the error
