### ISSUE TITLE
How to use a single sketchignore for entire repo which includes subdirectories?

### ISSUE THREAD

**Issue by jasonkylefrank** [mathieudutour/git-sketch-plugin#109]
When we have Sketch files in subdirectories of our repo, the root-level sketchignore is not used when we generate pngs.  I realize I can make a copy of the root-level sketchignore and put that into the subdirectories, but then we loose a single-source-of-truth.  

How do we enable the use of a single sketchignore which gets used no matter where the Sketch files are in subdirectories?

**Comment by mathieudutour** [comment]
very good point, I just realized that this morning.

We would need to traverse the directories tree from the sketch file to the root folder I guess.

**Comment by jasonkylefrank** [comment]
This would be a very good issue to resolve!

**Comment by mathieudutour** [comment]
Fixed in v0.11.0
