### ISSUE TITLE
Branches UI is blank

### ISSUE THREAD

**Issue by dustin-graham** [mathieudutour/git-sketch-plugin#110]
when I click on either the `branches` option or the `Preferences` option I can see a dialog window pop up, but it's blank. I've been trying to use the inspection tools to determine what can be done to fix this issue but I'm unfamiliar with CocoaScript. the inspector does not like the `let` variable definition. I changed them all to `var` in my local copy. Also, it doesn't like lambdas in branches.js. Wherever it sees a branch it  says "Unexpected Token `>`". Any ideas? The other scripts work correctly.

**Comment by davidrpoliti** [comment]
I have the same issue

**Comment by charles-waite** [comment]
I have the same issue. My Preferences screen is blank as well. Any update/fix for this?

**Comment by switzernator** [comment]
same issue here

**Comment by mathieudutour** [comment]
should be fixed in 0.10.1
