### ISSUE TITLE
Error "ambiguous redirect" when trying to Generate Pretty Diffs

### ISSUE THREAD

**Issue by charles-waite** [mathieudutour/git-sketch-plugin#111]
### How did it happen?
1. Working with an Atlassian Bitbucket repository, when I try to Git->Advanced->Generate files for pretty diffs I get this error. The same happens using Commit and checking the box for pretty diffs.

### Error log

```
~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin//exportArtboard.sh: line 36: ${readmeFile}: ambiguous redirect

```

**Comment by mathieudutour** [comment]
should be fixed in 0.10.1
