### ISSUE TITLE
Pretty diff files generation issue

### ISSUE THREAD

**Issue by pizzaeater** [mathieudutour/git-sketch-plugin#115]
1. Select menu Plugins/Git/Advanced/Generate files for pretty diffs
2. Shows me the error each time:

> /Users/user1/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin//exportArtboard.sh: line 36: ${readmeFile}: ambiguous redirect

**Comment by mathieudutour** [comment]
what version do you have? `v0.10.1` should fix it

**Comment by pizzaeater** [comment]
I use `v0.10.1`

**Comment by mathieudutour** [comment]
could you try with 0.11?

**Comment by pizzaeater** [comment]
Yep, it works! Thank you!
