### ISSUE TITLE
Hitting Github diff limit of 25

### ISSUE THREAD

**Issue by davidrpoliti** [mathieudutour/git-sketch-plugin#118]
Github has a diff limit for images, 25.
Is there a recommendation how organizing our files to work within this limit?

**Comment by mathieudutour** [comment]
Oh I didn't know there was a limit for it. I guess the only recommendation I could make is to keep your commits small.

I'm (unfortunately slowly) working on an app which could solve this: https://github.com/mathieudutour/git-sketch-plugin/issues/100

**Comment by davidrpoliti** [comment]
Thank you Sir!
This plugin is a lifesaver.
