### ISSUE TITLE
Version/Upgrade/Install issue?

### ISSUE THREAD

**Issue by jasonkylefrank** [mathieudutour/git-sketch-plugin#119]
I just tried to upgrade to your new `v0.11.0`, but I can't seem to get it installed. 

At first I thought maybe there was just a mistake in however Sketch reads the version number, since mine still showed `v0.9.1`.  But now I think maybe the new version of the plugin just won't install.  I'll explain.

I don't know what the "proper" way to do the upgrade is, but what I usually do to upgrade is I  download the zip and double clicking the `Git.sketchplugin` file.   I did that again this time.

Afterward I checked the version in Sketch (after restarting Sketch) and it still showed me being at `v0.9.1`.  I tried repeating the whole process again, but the result was the same.

I don't really know how you specify to Sketch what the version number is (not sure if the `package.json` gets read), but when I opened the `Plugins/Git.sketchplugin` in Atom, I was able to find a `manifest.json` file in `Contents/Sketch`, and I saw in there that it still said `0.9.1`:

![image](https://cloud.githubusercontent.com/assets/7502365/25766144/a8837f44-31be-11e7-9643-886f975aa780.png)

So then I thought maybe I was supposed to copy the `Git.sketchplugin` file into Sketch's `Plugins` folder.  So I did that, replacing the previous file.  However, **now I don't have the Git plugin installed at all**, even though the file is in the Plugins folder:

![image](https://cloud.githubusercontent.com/assets/7502365/25766268/6b5413c6-31bf-11e7-84c7-ceed8554b2a4.png)

So next I double clicked on the Git.sketchplugin file, both inside the Plugins directory and outside of that directory.  Restarted Sketch.  Still not installed.

Am I doing this wrong?  Should I have performed the upgrade differently?  And now how do I get it installed at all?

Thanks.

**Comment by mathieudutour** [comment]
Hum, where did you download the plugin?
From there: https://github.com/mathieudutour/git-sketch-plugin/releases ?

**Comment by arteforme** [comment]
Had the same issues when I downloaded via the "Clone or Download" button on the master branch.  Got it installed by down loading from the release page @mathieudutour linked.  See https://github.com/mathieudutour/git-sketch-plugin/issues/102

**Comment by jasonkylefrank** [comment]
Thanks @digita1-Anal0g, downloading from the releases page instead of the "Clone or Download" button on the master branch seems to have worked.

So is downloading from the "Clone or Download" button on master supposed to fail?

**Comment by mathieudutour** [comment]
Yes, I don't want to check in the generated code so the plugin is empty

**Comment by jasonkylefrank** [comment]
Thanks.
