### ISSUE TITLE
error when generating files for pretty diffs

### ISSUE THREAD

**Issue by hi-hu** [mathieudutour/git-sketch-plugin#12]
returns an error:
"/bin/bash: /usr/local/bin/sketchtool: No such file or directory"

**Comment by mathieudutour** [comment]
Did you install sketchtool?

**Comment by hi-hu** [comment]
Ah just did. Thanks for pointing it out. Resolved.

**Comment by mathieudutour** [comment]
feel free to create a PR if you feel that the readme wasn't clear enough ;)
