### ISSUE TITLE
initialize into existing path

### ISSUE THREAD

**Issue by astahl-CapGemini** [mathieudutour/git-sketch-plugin#120]
### How did it happen?
1. I used Sourcetree to clone the repo
2. Downloaded and installed git sketch plugin
3. Used Remote repo url to initialize plugin

Could be because I already have the files... but I wanted to use both: sourcetree and git sketch plugin (for the image diff). not possible?

### Error log

```
/Users/annestahl/.bash_profile: line 4: ^D: command not found
fatal: remote origin already exists.

```

**Comment by mathieudutour** [comment]
if you already have a git repo, just use `Advanced -> Add sketch file` to track your sketch file in git. You shouldn't have to initialise your repo
