### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by sxosxo** [mathieudutour/git-sketch-plugin#121]
### How did it happen?
From the Menu:
1. Init git repo (tried both https and with ssh key) 
2. Commit
3. Push

### Error log

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by patowod** [comment]
Same here, could someone please give a hint on how to solve this issue? Thanks in advance!

**Comment by mathieudutour** [comment]
does this help? ->
* https://help.github.com/articles/set-up-git/
* https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by 0xcaff** [comment]
Closing because you seem to be having issues with git, not with git-sketch-plugin.
