### ISSUE TITLE
Git not show in plugins list (Sketch 43.1)

### ISSUE THREAD

**Issue by alekseyruzov** [mathieudutour/git-sketch-plugin#128]
v0.11.1
The file added to Plugins folder:
![2017-05-18_12-14-05](https://cloud.githubusercontent.com/assets/4091432/26195155/857a450a-3bc3-11e7-9c3d-b5e9d386d5e7.png)

But in the plugins list is missing:
![2017-05-18_12-15-27](https://cloud.githubusercontent.com/assets/4091432/26195228/b68a8fba-3bc3-11e7-9f9b-9b1fdc270cc1.png)

![2017-05-18_12-17-44](https://cloud.githubusercontent.com/assets/4091432/26195313/0396a960-3bc4-11e7-832d-478847a9cccf.png)

**Comment by mathieudutour** [comment]
https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/FAQ.md#i-installed-the-plugin-but-its-not-showing-in-the-sketch-plugin-menu
