### ISSUE TITLE
Git Push Failed

### ISSUE THREAD

**Issue by hi-hu** [mathieudutour/git-sketch-plugin#13]
Received this message when using the Push tool. Although this is not a blocker since I can just push via command line. Great tool, ty!
–––
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: The current branch git-diff-test has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin git-diff-test
```

**Comment by mathieudutour** [comment]
I guess that running `git config --global push.default matching` should fix your problem

**Comment by hi-hu** [comment]
:ok_hand: :pray:
