### ISSUE TITLE
.bash_profile issues when generating files for pretty diffs

### ISSUE THREAD

**Issue by pixelbandito** [mathieudutour/git-sketch-plugin#130]
Could this be an issue using zshell with the plugin? I've ignored my .bash_profile for the last few years after switching to zshell and using a .zshrc file instead. I'm on Sketch version 43.2

### How did it happen?
1. I created a new git repo in github.
2. I checked out the empty repo to a directory on my machine.
3. I moved a sketch file to that directory.
4. I opened Sketch and used the Git plugin. I didn't init the repo in the plugin, because I know I'm already working in a local repo.
5. I tried using the Git plugin to add files. It said it was successful.
6. I tried using the Git plugin to push. It said it was successful.
7. I made a change to the file and used the Git plugin to commit. I checked the box for "Generate files for pretty diffs".
8. Errors ensued.

### Error log

```
/Users/cgarcia/.bash_profile: line 6: alias: gco: not found
/Users/cgarcia/.bash_profile: line 6: alias: =: not found
/Users/cgarcia/.bash_profile: line 6: alias: git checkout: not found
/Users/cgarcia/.bash_profile: line 9: alias: gc: not found
/Users/cgarcia/.bash_profile: line 9: alias: =: not found
/Users/cgarcia/.bash_profile: line 9: alias: git commit: not found
/Users/cgarcia/.bash_profile: line 19: /usr/share/git-core/git-completion.bash: No such file or directory
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages:"
     You should `unset PYTHONPATH` to fix this.

```

### .bashrc

```shell
# Shortcuts and junk
alias Finder='open -a Finder'
# alias subl='open -a "Sublime Text"'
alias flushdns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder'
alias gst='git status'
alias gco = 'git checkout'
alias gdev='git checkout dev'
alias gp='git pull'
alias gc = 'git commit'
alias bower='noglob bower'

# Git autocomplete
source /usr/share/git-core/git-completion.bash

# Ruby gems
source ~/.profile
```

**Comment by mathieudutour** [comment]
hum your .bashrc has some issues (all the ones reported: extra space before = and missing file)

I think it's fine to not have any thing in .bashrc, I just need a bash shell to find the path to git and python.

But it's weird that it worked for adding and pushing because it's using the same shell.

Not sure I can do much here

**Comment by pixelbandito** [comment]
I'm an idiot. Thank you. I cleaned up the .bashrc file, and everything's cool.

I guess it failed silently when using git add, git commit, etc.
