### ISSUE TITLE
Stack while committing

### ISSUE THREAD

**Issue by chanjohnathan** [mathieudutour/git-sketch-plugin#131]
### How did it happen?
1. Made some changes to my sketch file
2. Saved (CMD + S)
3. Committed

Doesn't always do it, often does it a few seconds (between 5-20 secs) after I save.

Sketch 42.36781, OS X 10.11.6

### Error log

```
/Users/studio/.bash_profile: line 33: /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh: No such file or directory

```

**Comment by mathieudutour** [comment]
hum could you try installing the command line tools? http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by j7nc2n** [comment]
Done! I'll let you know if I keep getting the message. Thanks!

**Comment by j7nc2n** [comment]
Now I'm getting these messages:

```
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```

and after I push:

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

After 4 tries I was able to commit. The file wasn't in an interim save state.

**Comment by mathieudutour** [comment]
Did you add your sketch file to be tracked on git? It seems that git doesn't find any changes to the files in your repo.

Can't do much here, that's a git issue

**Comment by j7nc2n** [comment]
Yes, the file was tracked prior to using the plugin. Might be a mixed issue as I never encountered any error of this type while using Git. Thanks for the pointers!
