### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AGuyNamedMarco** [mathieudutour/git-sketch-plugin#136]
My system:
• OS X v10.11.5
• Sketch v44.1

Hi there. 

Thanks for writing this plugin!

I noticed you addressed this issue in your FAQ but the answer didn't address my issue.

I've tried installing v0.11.2 of your plugin (from [here](https://github.com/mathieudutour/git-sketch-plugin/releases/tag/v0.11.2)) but it never appears in my Plugins menu.

It also never gets added the my Plugins folder (/Users/marcomendoza/Library/Application Support/com.bohemiancoding.sketch3).

**Comment by mathieudutour** [comment]
never gets added to the folder? weird. Can you try to just drag and drop it to the folder?

**Comment by AGuyNamedMarco** [comment]
So I tried manually adding it to my Plugins folder.

I also tried installing it via [Runner](http://sketchrunner.com/), and that added it to my folder as well.

But I'm still not seeing it within Sketch's Plugin dropdown menu.

**Comment by mathieudutour** [comment]
So not seeing it when installing with Runner is expected because they don't pick the right file.

**Comment by lukas-ther** [comment]
This issue is also happening to me - after installing the plugin file shows up in the plugin sketch folder but it won't show up in the dropdown menu.
<img width="291" alt="screen shot 2017-06-16 at 09 40 41" src="https://user-images.githubusercontent.com/23483910/27217268-744351ce-5279-11e7-84aa-dd474a367301.png">

**Comment by mathieudutour** [comment]
did you installed it from the release page?

**Comment by mathieudutour** [comment]
can you right click on the plugin -> show package content and tell me what is inside?

**Comment by lukas-ther** [comment]
thanks for advice, installing plugin from release page worked (before that I downloaded master zip)
