### ISSUE TITLE
Git commit for project stopped working (not a git repository)

### ISSUE THREAD

**Issue by meirion** [mathieudutour/git-sketch-plugin#139]
### How did it happen?
1.  Plugins > Git > Commit
2. tried to create a commit for a pre-existing git project. No idea why it used to work but doesn't now.  I haven't made a commit for a couple of weeks.
3.

### Error log

```
fatal: Not a git repository (or any of the parent directories): .git

```

**Comment by mathieudutour** [comment]
hum not sure. Did you move your file?
