### ISSUE TITLE
Error when generating files for pretty diff

### ISSUE THREAD

**Issue by marionebl** [mathieudutour/git-sketch-plugin#14]
When generating pretty diffs a `Failed...` error message pops up, and no commit on the repository is performed.
#### Commiting
- Edit/add a sketch file in a git repository
- Show commit prompt via `Plugins > Git > Commit`
- `Generate files for pretty diffs` is ticked
- Enter commit message, hit `Commit``
##### Direct Invocation
- `Plugins > Git > Generate files for pretty diffs`
### Error message:

``` log
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: 
attempt to insert nil object from objects[3]
((null) ECCommandLineDomain:5)
```
### Used versions:

```
❯ chest list
(git)   git-sketch-plugin bb101a3bbc77947bb7c6890b5c4600b962b43bf9

❯ sketchtool -v
sketchtool Version 3.5.2 (25235)
```

**Comment by marionebl** [comment]
Any ideas? I'd be glad to help out, just need a pointer in the direction.

**Comment by mathieudutour** [comment]
Not really. What happen if you try to call `sketchtool` directly from the command line?
`sketchtool export artboards name_of_your_file --output=.exportedArtboards/ --overwriting=YES`

**Comment by mathieudutour** [comment]
(very nice bug report btw)

**Comment by davids701124** [comment]
This happens on my side as well.

**Comment by marionebl** [comment]
``` bash
sketchtool export artboards name_of_your_file --output=.exportedArtboards/ --overwriting=YES
```

produces the same error as printed in the GUI:

```
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]
((null) ECCommandLineDomain:5)
```

Appears to be a problem with sketchtool itself. Will ping Bohemian Coding about it.

**Comment by marionebl** [comment]
It appears to me this was a combined issue with an out-of-sync copy of `sketchtool` and missing fonts. Perhaps mentioning the requirement that all used fonts **have** to be installed before generating diffs would be beneficial – best case would be an error message reflecting this.

**Comment by mathieudutour** [comment]
Oh I didn't know about this requirement.
I'm not sure we can catch this specific error, the error message is quite generic. But we can specify it in the readme.
Want to create a PR for it?
