### ISSUE TITLE
Typo: wrong filename in download description

### ISSUE THREAD

**Issue by Tobbyte** [mathieudutour/git-sketch-plugin#143]
on the [releases page](https://github.com/mathieudutour/git-sketch-plugin/releases/tag/v0.11.2) it says "download this file, unzip and double click on the **.sketchfile**", but the file is actually called ".sketchplugin"

**Comment by mathieudutour** [comment]
Thanks! fixed here: https://github.com/skpm/skpm/commit/a39eb8e20d4301093ea86284ab627ad5a6544de6
