### ISSUE TITLE
Merge conflicts

### ISSUE THREAD

**Issue by IanCStewart** [mathieudutour/git-sketch-plugin#148]
# The issue

```
➜  sketch git:(issue-#6) git merge develop --no-ff
Auto-merging ui.sketch
CONFLICT (content): Merge conflict in ui.sketch
Automatic merge failed; fix conflicts and then commit the result.
Encountered 1 file(s) that should have been pointers, but weren’t:
    ui.sketch
```

When there is a conflict in a branch you are trying to merge there is no possible way to fix this.

## Reproduce

1. make changes in 2 separate branches.
2. merge 1 to 'develop'
3. get merge conflicts in the remaining branch
4. merge 'develop' with the remaining branch through terminal
5. get stuck trying to open sketch (sketch thinks this file is broken now...)

**Comment by mathieudutour** [comment]
The plugin doesn’t handle merging sketch files. Check out https://github.com/kactus-io/kactus
