### ISSUE TITLE
git-lfs: command not found

### ISSUE THREAD

**Issue by shanecarmody** [mathieudutour/git-sketch-plugin#15]
I’m getting an error when I try to commit, it’s something to do with `git-lfs` but I don’t fully understand what it means.
- I ran the `git lfs install && git lfs track '*.png' && git lfs track '*.sketch' && git add .gitattributes` at the before trying to commit anything. 
- I made some changes to the names of my **Artboards**
- I saved
- I committed using the Git plugin UI
- I then got this message:

<img width="532" alt="capture d ecran 2016-03-07 a 11 40 57" src="https://cloud.githubusercontent.com/assets/433990/13567123/b56d1296-e459-11e5-8da5-b2e0188cfbe8.png">

`git-lfs clean '.exportedArtboards/Jellyfish/1-Dashboard.png': git-lfs: command not found
error: external filter git-lfs clean 0.000000 failed -1
error: external filter git-lfs clean 0.000000 failed
fatal: .exportedArtboards/Jellyfish/1-Dashboard.png: clean filter 'lfs' failed`

Any idea what’s causing the error? I don’t understand why it says `git-lfs: command not found` when I got the `Git LFS initialized.` message after running the `git lfs install` command.

**Comment by shanecarmody** [comment]
i’m using `sketchtool Version 3.5.2 (25235)` if that helps in any way.

**Comment by mathieudutour** [comment]
does `which git-lfs` return anything?

**Comment by shanecarmody** [comment]
Yep, it returns `/usr/local/bin/git-lfs`

**Comment by mathieudutour** [comment]
@loklaan any idea?

**Comment by loklaan** [comment]
Try having git and git-lfs in the same directory - use symlinks.
More info here https://github.com/github/git-lfs/issues/846#issuecomment-159615668

**Comment by shanecarmody** [comment]
For some unknown reason, it seems to work today… I’m puzzled, would a restart have made a difference?

**Comment by mathieudutour** [comment]
It might have, maybe your PATH was a bit broken or something.
Closing for now but feel free to re-open if it comes back.

**Comment by maxjgoldberg12** [comment]
This is happening to me right now when I try to commit inside the sketch plugin UI. I have sketchtool, git, and git-lfs all installed at `/usr/local/bin/`. I can do everything fine with git commands from the terminal, but the commit UI command throws the same error that @shanecarmody reported. 

I'm running OSX 10.11.3, git 2.7.2, sketchtool 3.6.1

**Comment by shanecarmody** [comment]
@maxjgoldberg12 did you try restarting your machine? That seemed to do it for me. Otherwise, did you try the solution @loklaan linked to?

**Comment by maxjgoldberg12** [comment]
@shanecarmody Yes, I restarted and the same error occurred :cry:  I also tried changing the symlink at `/usr/local/bin/git` from my homebrew 2.7.2 git to the embedded Apple git that's at `/usr/bin/git` and saw the same error. 

Again, it all works from the terminal, but the Commit option in the Sketch plugin seems to be doing something different.

**Comment by mathieudutour** [comment]
what happen if you run `/bin/bash -c "git commit -m 'test' -a"` in your repo?

**Comment by nandorocker** [comment]
+1 here. Same problem; restarted, sym-linked, no luck.

I ran @mathieudutour 's command:

```
[sameboard 3d5a349] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite file1.sketch (100%)
```

**Comment by luchomolina** [comment]
+1 here. Commits via terminal/GitHub app work fine.

**Comment by edennington** [comment]
+1 here. Having the same issues cited above.

**Comment by mathieudutour** [comment]
Ok I think I fixed it.
Can any of you (@edennington, @luchomolina, @nandorocker) confirm?

**Comment by luchomolina** [comment]
@mathieudutour Worked! Thanks.
