### ISSUE TITLE
Make it installable via "runner"

### ISSUE THREAD

**Issue by mackelito** [mathieudutour/git-sketch-plugin#158]
Would be great if we could install the plugin using Runner

**Comment by mathieudutour** [comment]
no, supporting Runner would mean that I need to commit generated files which is terrible. So it's up to them to support download links and not raw github repo

**Comment by mackelito** [comment]
ok I understand.. just being curious here but why is that terrible?

**Comment by mathieudutour** [comment]
because as soon as 2 people work at the same time, there are tons of conflicts. Same reason you shouldn't commit any build file really. (kind of the same reason it's really hard to use git with sketch files, and why Kactus is useful)
