### ISSUE TITLE
Have to close Sketch when switching branches

### ISSUE THREAD

**Issue by shanecarmody** [mathieudutour/git-sketch-plugin#16]
The plugin is working great. An issue I’ve noticed, however, is that when switching branches I have to:
1. Close Sketch 
2. Switch branch _git checkout branch-name_ 
3. Reopen Sketch

This isn’t that annoying, it’s just that in order for the updates from a branch to take effect in Sketch I have to close it while switching between branches. 

Would there be any way to reload the file after having switched branches?

Thanks for the great plugin :+1:

**Comment by mathieudutour** [comment]
I experimented without any luck for now.

**Comment by mathieudutour** [comment]
duplicate #2
