### ISSUE TITLE
Web Inspector of Safari opens in each action

### ISSUE THREAD

**Issue by ikasoumen** [mathieudutour/git-sketch-plugin#160]
### How did it happen?
When using Safari and this plugin at the same time, Safari's Web Inspectors are automatically opened  in each action and stacked on desktop.

### Error log
no error

**Comment by ikasoumen** [comment]
Excuse me. I've found this problem happens with other sketch plugins, so I will check Sketch.app forum or kinds like that.

**Comment by mathieudutour** [comment]
on Safari, Develop > Your Machine > uncheck Automatically show inspector

**Comment by ikasoumen** [comment]
Thank you, @mathieudutour !
