### ISSUE TITLE
plugin cannot be installed with version 47.1

### ISSUE THREAD

**Issue by chemidy** [mathieudutour/git-sketch-plugin#163]
Hi,

With Sketch 47.1, when i try to install the sketch plugin nothing happens.

Any idea ?

**Comment by mathieudutour** [comment]
https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/FAQ.md#i-installed-the-plugin-but-its-not-showing-in-the-sketch-plugin-menu
