### ISSUE TITLE
Cannot locate Git-Sketch-Plugin within Plugins menu

### ISSUE THREAD

**Issue by EdemAttiogbe** [mathieudutour/git-sketch-plugin#165]
After installing the Git-Sketch-Plugin, it doesn't show up within my Plugins menu within Sketch, but it is indeed installed (please reference attached screen-shot for review).  Is there something else I need to do?  I'm currently using Sketch version 46.2

![screen shot 2017-12-09 at 6 19 13 pm](https://user-images.githubusercontent.com/24817745/33801346-c2453cce-dd0d-11e7-862c-07a47e4b94ce.png)

**Comment by mathieudutour** [comment]
this plugin manager doesn't know how to install this plugin because it makes assumptions that are wrong. Install it manually: https://github.com/mathieudutour/git-sketch-plugin#installation

**Comment by EdemAttiogbe** [comment]
Thanks.  Manual installation worked perfectly.
