### ISSUE TITLE
Generate CSS output

### ISSUE THREAD

**Issue by good-idea** [mathieudutour/git-sketch-plugin#169]
It would be great to see visual differences as well as that of some kind of CSS output.

I'm a developer, and when my designer makes changes, if I could see different CSS values, this would mean that I would not have to open sketch, find the artboard, click around to find the new value.

More or less:

```
BIN [] [] [] example/.exportedArtboards/example/Artboard 1.png

          Deleted                    Added
   +++++++++++++++++++++       +++++++++++++++++
   |                   |       |               |
   |☃                  |       |       ☃       |
   |                   |       |               |
   +++++++++++++++++++++       +++++++++++++++++

2 [] [] [] example/.exportedArtboards/example/Artboard 1.css

   .Artboard_1 {                  .Artboard_1 {
      width: 100px;           -     width: 100px;
                              +     width: 75px;
                              +     text-align: center;
   }                              }
```

(If you can't tell, I'd prefer to not open anything other than my editor for most tasks, including drawing..)

If this sounds like it would be a valuable and tenable addition to the plugin, I'd be happy to dig in and make a PR. I'd just need to be pointed in the right direction: I'm new to git-sketch-plugin, and also not sure what CSS exporting options there are that would be good to use.

Bonus if it could do the same for Text and Object Styles!!

**Comment by 0xcaff** [comment]
Generating CSS is hard. When generating CSS there are multiple ways to express the same layout. You could use grid, flexbox or `text-align` and inline elements to express the same layout.

A similar tool to the one you describe already exists. It is called [kactus](https://kactus.io/). It has an intermediate JSON format which can be diffed to show what exactly changed and how it changed. It doesn't generate CSS (AFAIK).

**Comment by good-idea** [comment]
Ah, I didn't know Kaktus outputs JSON, I'll take a look. I do know that any CSS exported from sketch isn't going to necessarily match what I'd actually be using in development - but often it would be easy to infer what changes needed to be made by seeing values instead of images.

Thanks for the fast reply!
