### ISSUE TITLE
Not seeing the unchanged file, just the final output file.

### ISSUE THREAD

**Issue by morecoffeyplease** [mathieudutour/git-sketch-plugin#17]
Here are the steps I'm taking:
1. Checkout master
2. Plugins > Git > New Branch > name Branch
3. Make changes
4. Plugins > Git > Commit > enter message (leave checkbox checked for pretty diffs)
5. Plugins > Git > Push

But when I go to open a pull request on github.com, all I can see is the final output diff image. Here's where you can see what I'm talking about: https://github.com/sfotyler/sketch/compare/added_hat?expand=1.

Not sure if I'm doing something wrong. I  L O V E this idea, thank you very much for the work and the help on this issue.

**Comment by mathieudutour** [comment]
because there is no image in your master branch

**Comment by morecoffeyplease** [comment]
Aha got it, thanks for the tip.
