### ISSUE TITLE
Why if i use a git client i can commit, push, etc. and if i use the plugin i receive this error?

### ISSUE THREAD

**Issue by vinzaceto** [mathieudutour/git-sketch-plugin#170]
### How did it happen?
1. i modified my sketch file
2. i commit the file using the plugin
3. i tried to push the commit with the plugin

### Error log

```
remote: Repository not found.
fatal: repository 'https://github.com/vinzaceto/madeInChain.git/' not found

```

**Comment by 0xcaff** [comment]
That's a strange problem. This plugin uses the `git` client on your `PATH`. 

https://github.com/mathieudutour/git-sketch-plugin/blob/f4bc6bca880ca16a98aaaba8b56241d26daa34f1/src/commands/Push.js#L9

Does running the following command fail also?

```
git -c push.default=current push -q
```

What `git` client are you using?
