### ISSUE TITLE
All artboards show being "changed" after a Sketch update

### ISSUE THREAD

**Issue by jasonkylefrank** [mathieudutour/git-sketch-plugin#174]
The great about this plugin is being able to see what you changed with each commit.  Normally that works pretty well.

But sometimes we literally only make one artboard change and then when we go to commit it shows that every single artboard in the file has been "changed".  I am not totally sure, but I think this happens when we edit a Sketch file that was created using a previous version of Sketch.

So the scenario goes like this:

1.  We create a Sketch file and it ends up having lots of artboards.
2. Sketch releases a new version (not sure if minor versions do it or major versions)
3. We edit the Sketch file and export PNG images.
4. We go to commit and it shows hundreds of artboard changes (see the screenshot for an example from today: 512 changes).

![image](https://user-images.githubusercontent.com/7502365/38049070-2f6a869c-3295-11e8-8427-20cef8eaaf94.png)

This has happened to us with many different files.  And it makes the process of seeing "what has changed" pretty much impossible when this problem occurs.

**Comment by mathieudutour** [comment]
can't do much about it. a sketch update might slightly change the exports without being visible to the naked eye. Just create a commit when you update Sketch and it should be fine
