### ISSUE TITLE
Could not read Username for 'https://github.com': Device not configured

### ISSUE THREAD

**Issue by skybluemizu** [mathieudutour/git-sketch-plugin#178]
### How did it happen?
1. I've commited changes
2. I've wanted to push into remote repo
3. and got this message

<img width="414" alt="screen shot 2018-05-17 at 13 05 44" src="https://user-images.githubusercontent.com/33522601/40177940-ed244722-59d7-11e8-8a9d-b7ec2a9c281e.png">

Never had option to connect, do I have to use terminal to log in?

### Error log

```
fatal: could not read Username for 'https://github.com': Device not configured

```

**Comment by 0xcaff** [comment]
Duplicate of #95
