### ISSUE TITLE
fatal: repository 'https://github.com/new/' not found

### ISSUE THREAD

**Issue by april9009** [mathieudutour/git-sketch-plugin#179]
I initiated the repo to my remote address, checkout a brand and commit the change, when I try to push the new version to the master, I got the following error:
remote: Not Found
fatal: repository 'https://github.com/new/' not found

My remote is not https://github.com/new/, why do I encounter this error?

**Comment by mathieudutour** [comment]
You need to create a repo and enter its URL, not `/new`
