### ISSUE TITLE
Error Occures when Genrate files for pretty diffs

### ISSUE THREAD

**Issue by OtaYohihiro** [mathieudutour/git-sketch-plugin#180]
### How did it happen?
1. Some file changed.
2. Try to commit with `genrate files for pretty diffs` checked
3. Error occured

### Error log

```
2018-06-11 11:42:47.235 sketchtool[99040:12015171] *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
  File "<string>", line 1
    import urllib;print urllib.quote(raw_input())
                             ^
SyntaxError: invalid syntax

```

### ScreenShot
![errormessage](https://user-images.githubusercontent.com/11780894/41210845-e5df2d38-6d6e-11e8-8bd2-d33ba0420230.png)

### Environment
- MyPC
  - MacOS : Sierra 
  - Version : 10.12.6（16G1036）
- Sketch Version : 50.2
- git-sketch-plugin Version: 0.11.3

**Comment by mathieudutour** [comment]
fixed in 0.12
