### ISSUE TITLE
Unable to install the plugin with sketch 51

### ISSUE THREAD

**Issue by l-landier** [mathieudutour/git-sketch-plugin#184]
Hi, 
I used your plugin with sketch, it worked well, 
but I recently upgraded to sketch 51 and now I can't install the plugin, when I double-click on Git.sketchplugin it doesn't do anything, 

I think it's a problem from the new update sketch made.

Can you look into it please? 

Thank you.

**Comment by mswanson** [comment]
I was having a problem with installing v0.11.4 but I got v0.11.3 to install properly

**Comment by samelliott89** [comment]
Seconded.

**Comment by mathieudutour** [comment]
fixed in 0.12
