### ISSUE TITLE
Error when commit

### ISSUE THREAD

**Issue by robjalkh** [mathieudutour/git-sketch-plugin#19]
<img width="379" alt="screen shot 2016-03-23 at 10 13 27 am" src="https://cloud.githubusercontent.com/assets/7140772/14000930/79bc9aa4-f111-11e5-9020-23700be6ec4d.png">

Do you guys know, why I'm not being able to commit. I already have installed sketchtool

**Comment by mathieudutour** [comment]
what happened when you run `which sketchtool` in a terminal?
