### ISSUE TITLE
Adapt plugin for Adobe XD

### ISSUE THREAD

**Issue by lucasafranio77** [mathieudutour/git-sketch-plugin#190]
Hi,

adobe xd is now open for plugins. 
Would it be possible to adapt this versioning plugin to work with adobe xd?

https://adobexdplatform.com/

Congratulations for works.

**Comment by 0xcaff** [comment]
Not really, it would be pretty hard I think. Adobe XD is planning to add version control. https://adobexd.uservoice.com/forums/353007-adobe-xd-feature-requests/suggestions/18981772-revision-control
