### ISSUE TITLE
Issue with 0.11.3

### ISSUE THREAD

**Issue by michaelfalkner** [mathieudutour/git-sketch-plugin#191]
Hey,

So I recently downloaded MacOS Mojave and installed Sketch Version 52.2 along with your Git Plugin 0.11.3. When I install 0.11.3 it opens my sketch but I do not get a success message nor does it go into my plugins folder. I tried dragging the plugin to the folder without installing with no success. 

lastly, I decided to try an old version of the plugin, 0.11.2 and that was successful.

Not sure if this is a common problem, but wanted to make you aware.

**Comment by mathieudutour** [comment]
fixed in 0.12
