### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [mathieudutour/git-sketch-plugin#194]
Hi, what is the current status of this project? Is it still maintained?

**Comment by mathieudutour** [comment]
> This plugin was a first attempt to bring version control and collaboration to designers. Since then, Sketch evolved a lot and my new project takes advantages of them to unlock true version control. Check it out: http://kactus.io

**Comment by DanielRuf** [comment]
Ah ok, oversaw thus while checking the last commit and issues. Is kactus now 100% opensource?

**Comment by DanielRuf** [comment]
Ah ok, oversaw this while checking the last commit and issues. Is kactus now 100% opensource?

**Comment by mathieudutour** [comment]
it has always been

**Comment by DanielRuf** [comment]
But there are limitations afaik like the available platforms and so on. Or can we enable these features by doing some changes in the code?

**Comment by mathieudutour** [comment]
available platforms? It only works for mac yes, but that's because it needs Sketch

**Comment by DanielRuf** [comment]
No I meant the platforms that we can use for the Git repos.

I mean the Enterprise features: https://kactus.io/pricing/

Which seems like features are not opensource (backend, integrations / Git providers, ...).

**Comment by mathieudutour** [comment]
There is a difference between open source and free. It's open source but I kindly ask you to buy a license when you use a private/enterprise repo since it usually means you use it in your company to make money.
Otherwise, I won't have any means to spend time on it to release updates

**Comment by DanielRuf** [comment]
Sure, but this does not answer my question if the opensource repo has all the features for example to continue working with it also in 5+ years. Also my focus is currently to check how we (opensource and free sideprojects) could use it with our selfhosted GitLab instances (not the instance at work, just the one from us volunteers working on esports and opensource projects which is managed by me).

Or would we have to buy an enterprise license for every team?

**Comment by mathieudutour** [comment]
As I said, it had always been 100% open source.

I'd be happy to give licenses to any open source projects if that helps. And once you have a license, you can use Kactus with any repo.

**Comment by DanielRuf** [comment]
Okay, thanks for the info and clarification. I'll discuss it with the project teams and how much budget we would have.
