### ISSUE TITLE
Error when commit

### ISSUE THREAD

**Issue by bloombar** [mathieudutour/git-sketch-plugin#202]
### How did it happen?
1. Saved sketch app file into a directory that already was a clone of a GitHub repo
2. Tried Advanced->Add file to git... that works fine
3. Tried Push... that also works
4. However, Commit crashes each time with an Objective C error, regardless of whether I have first added, pulled, or pushed to/from git

![image](https://user-images.githubusercontent.com/2209098/54387955-04f72580-4673-11e9-95ad-fc672c4dd634.png)

### Error log

```
{
	"nativeException": {},
	"line": 195,
	"column": 37,
	"sourceURL": "/NoneOfYourBusiness/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/Commit.js"
}
```

**Comment by mathieudutour** [comment]
fixed in 0.12
