### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by arttema** [mathieudutour/git-sketch-plugin#208]
### How did it happen?
1. tried to commit an init commit with generated previews (200MB file)
2. waited for 10 minutes and killed sketch
3. committed again init commit without commit name and without previews
4. got bug constantly
5. uninstalled the extension
sketch 54.0

### Error log

```
{
	"nativeException": {},
	"line": 195,
	"column": 37,
	"sourceURL": "/Users/artyom/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/Push.js"
}
```

**Comment by mathieudutour** [comment]
fixed in 0.12
