### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GiuseppeMobiDev** [mathieudutour/git-sketch-plugin#26]
{
    column = 25;
    line = 11;
    sourceURL = "/Users/workstation001/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/Init.cocoascript";
}

**Comment by mathieudutour** [comment]
Any more information? That's not really useful... What were you doing? How is your directory? etc.
