### ISSUE TITLE
Doesn't work on Sketch 3.5

### ISSUE THREAD

**Issue by HYPD** [mathieudutour/git-sketch-plugin#3]
After typing in commit message or when trying to generate pretty diffs, I receive the following error:

`2016-01-27 12:43:17.856 sketchtool[31862:11553973] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-01-27 12:43:17.857 sketchtool[31862:11553973] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
Failed to open document Playlist.sketch -- file:///Users/danross/design-android/
((null) MSDocumentDomain:11)`

**Comment by mathieudutour** [comment]
Looks like a bug in `sketchtool`. Do you have the lastest version of both sketchtool and Sketch?

**Comment by hpizaia** [comment]
I had the same problem using the last version of Sketch 3.5.1 and Sketch Tool 3.4.

**Comment by mathieudutour** [comment]
They just released a new version of Sketch indeed. They might not have updated `sketchtool` yet.

**Comment by mathieudutour** [comment]
@HYPD can you confirm that you are also using Sketch 3.5?

**Comment by danoreowong** [comment]
I'm using Sketch 3.5.1 - and I get the same error. 
![image](https://cloud.githubusercontent.com/assets/1332545/12615244/6bdc5802-c4fc-11e5-8a15-a6cbdd02b3b8.png)

**Comment by mathieudutour** [comment]
From the Sketch release notes

> Like all previous updates, please note that Sketch 3.5 files are not backwards compatible with earlier versions.

I just checked, sketchtool hasn't been updated yet.

**Comment by AlexandreBroudin** [comment]
Yes same problem here.
Wanted to try with sketch 3.5.1

**Comment by cphilippsen** [comment]
Same issues as above on 3.5.1, waiting for a sketchtool update then :+1:

**Comment by mathieudutour** [comment]
the new sketchtool comes bundled with the Sketch app. It does work when you update it.
http://www.sketchapp.com/tool/

**Comment by HYPD** [comment]
Sorry for the late reply, I can confirm this was happening on Sketch 3.5.1 - Fixed as per your instructions.
