### ISSUE TITLE
Commit Error: resources.bundle doesn't exist?

### ISSUE THREAD

**Issue by yisraelgrimes** [mathieudutour/git-sketch-plugin#33]
Testing out the plugin. I first got an error that it couldn't find the sketchtool files so I installed it via terminal. Now I get this error. I'm guessing it's user error but I'm not sure what am I doing wrong here? 

Thanks in advance for the help!!

![screen shot 2016-05-20 at 3 46 42 pm](https://cloud.githubusercontent.com/assets/10249711/15441811/a383b980-1ea2-11e6-8d2b-467f77e47b0c.png)

**Comment by mathieudutour** [comment]
You don't need to install the sketchtool anymore, I'm looking for it directly in the sketch app bundle. Not sure what is happening here... 
Where is you app installed?
Is there still sketchtool inside?

**Comment by yisraelgrimes** [comment]
Mine is showing in the package contents inside Sketch. The Sketchtool folder is still there. But to be honest, I'm not the most proficient when it comes to command line. I usually use a GUI like Sourcetree for my git stuff. 
![screen shot 2016-05-21 at 10 07 29 am](https://cloud.githubusercontent.com/assets/10249711/15449184/38964b2a-1f3c-11e6-9e10-d2a25f7be733.png)

**Comment by mathieudutour** [comment]
how did you install sketchtool exactly?

**Comment by yisraelgrimes** [comment]
Drag and drop the install.sh into terminal, cross my fingers, and press return :)

**Comment by mathieudutour** [comment]
that's the right way to install it ;)

I don't manage to repro. I published a few changes today, maybe try to use the new version?

**Comment by yisraelgrimes** [comment]
Woowhoo!
Updated the plugin and it looks like the commits are working. I got an error when I tried to create a new branch within Sketch but that isn't that big of a deal to me. The main thing that matters to me is committing and creating the pretty difs.

**Comment by mathieudutour** [comment]
oh nice!

I'm closing this issue but feel free to open a new one with branch problem.

**Comment by yisraelgrimes** [comment]
Sounds good. Thanks for the help!
