### ISSUE TITLE
Error on Commit when using NVM and AVN

### ISSUE THREAD

**Issue by ryanjohnstone** [mathieudutour/git-sketch-plugin#34]
My guess is the plugin is CDing to the directory and avn is being activated to change the node version, the plugin is receiving the output of this as feedback from the commit and assuming it has failed because it's not what it was expecting. 

<img width="420" alt="screen shot 2016-05-26 at 09 44 52" src="https://cloud.githubusercontent.com/assets/8439440/15568982/a8f83f16-2326-11e6-86cb-b3e443af686d.png">

**Comment by mathieudutour** [comment]
indeed. looks like avn is writting to sdterr?

**Comment by whoisbohn** [comment]
Getting a similar error when trying to commit:

![screen shot 2016-06-30 at 4 58 16 pm](https://cloud.githubusercontent.com/assets/675817/16504037/e569d6ca-3ee3-11e6-90da-56de213d1f20.png)
