### ISSUE TITLE
Unsure how to point this plug-in at an existing repo

### ISSUE THREAD

**Issue by rnicholus** [mathieudutour/git-sketch-plugin#35]
After installing the plug-in, and following the first setup step, I am faced with an error. Something about the remote origin already existing (which is definitely not the case). I'd much rather just create a repo myself, clone, and then point git-sketch-plugin at the directory that houses my cloned repo. How can I accomplish this?

**Comment by mathieudutour** [comment]
if your file is already in a repo, you just have to add it to git (`git add name_of_the_file` or `plugins > git > advanced > add file to git`).

**Comment by mathieudutour** [comment]
not sure what is the issue

**Comment by rnicholus** [comment]
...but how does your plug-in know which repo/directory?

**Comment by mathieudutour** [comment]
it's the directory your sketch file is in

**Comment by rnicholus** [comment]
Just to be clear, the following workflow is supported:
1. Create a git repo
2. `git clone` the repo locally
3. Save/move sketch file to this locally cloned repo
4. Commit/push changes to the sketch file via your plug-in. "Pretty-diffs" will be generated & committed as well.

I'm not exactly certain what "pretty diffs" are, but is the above correct?

**Comment by mathieudutour** [comment]
yes. You do have to add the file to git though (as described earlier)

**Comment by rnicholus** [comment]
Great, thanks! One more thing regarding pretty diffs. Is this just a .png that makes it easier to compare sketch files via the GitHub UI? Or is it something else...

**Comment by mathieudutour** [comment]
it's one png file per artboard

**Comment by rnicholus** [comment]
Cool, thanks again for your support and for your work on this plug-in.
