### ISSUE TITLE
Plugin installed but not working on Sketch 3.8.2

### ISSUE THREAD

**Issue by pascalhuynh** [mathieudutour/git-sketch-plugin#36]
Hi,

I just installed this plugin on my Sketch version 3.8.2 but I keep getting an error message on every action the plugin allows me to do (e.g. init the repo).

```
{
    column = 37;
    line = 37;
    sourceURL = "/Users/pascal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/Init.cocoascript";
}
```

**Comment by mathieudutour** [comment]
oh sorry, I messed it up yesterday. Should be fix now

**Comment by pascalhuynh** [comment]
Thanks, I can now create a repo / create a branch / commit / push. But I still get an error when I want to visualise the diff.
Below the error we get:

/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file

**Comment by mathieudutour** [comment]
d'oh. Still sleepy ;) Should be ok now

**Comment by pascalhuynh** [comment]
Thanks, it’s working now. Great job !
