### ISSUE TITLE
can't commit with single apostrophes in comments

### ISSUE THREAD

**Issue by spicemix** [mathieudutour/git-sketch-plugin#38]
Try to commit with ' in a comment e.g.

`fix it's problem`

Result:

> **Failed...**
> 
> /bin/bash: -c: line 0: unexpected EOF while looking for matching `''
> /bin/bash: -c: line 1: syntax error: unexpected end of file

**Comment by mathieudutour** [comment]
Thanks for pointing it out! Should be fixed in the new version

**Comment by spicemix** [comment]
Tried the new rev...was crashing right out of Sketch on any commit. Rolled back and am fine, but for the ' bug of course.

**Comment by mathieudutour** [comment]
oh sorry about that, my bad 👎 , should be fixed now

**Comment by spicemix** [comment]
All good thanks very much... fantastic plugin
