### ISSUE TITLE
Failed to init

### ISSUE THREAD

**Issue by Davehellbent** [mathieudutour/git-sketch-plugin#39]
Hello - I get the error pasted below after installing the plugin and attempting to Init the repo
Plugins > Git > Advanced > Init git repo
I use Sketch v3.8.3
{
    column = 23;
    line = 61;
    sourceURL = "/Users/USER/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/Init.cocoascript";
}

**Comment by mathieudutour** [comment]
I can't reproduce. Any specificities in your folder?

**Comment by Davehellbent** [comment]
Nope. Fresh Sketch Install and fresh plugin install...

**Comment by Davehellbent** [comment]
Uninstalled plugin, reinstalled and failed again:(

**Comment by akeelnazir** [comment]
+1

**Comment by mathieudutour** [comment]
Is your file saved in a weird folder (like dropbox or google drive) ?

**Comment by akeelnazir** [comment]
No, it's in the `~/Library/Application Support/com.bohemiancoding.sketch3/Plugins` folder

**Comment by mathieudutour** [comment]
what? Your sketch file file is there?

**Comment by akeelnazir** [comment]
oh no, sketch file is in my Documents folder

**Comment by mathieudutour** [comment]
hum maybe git doesn't want to create a repo there.

What happen if you dowload this repo as a zip, open the sketchfile in example/ and init the repo?

**Comment by akeelnazir** [comment]
just tried uninstalling the plugin and reinstalling it again. Somehow it works now 👍 

Thanks guys. It works like a charm.

**Comment by mathieudutour** [comment]
¯_(ツ)_/¯
