### ISSUE TITLE
Cannot be used within an App Sandbox

### ISSUE THREAD

**Issue by ghost** [mathieudutour/git-sketch-plugin#4]
When I try to run any of the actions in the plugin menu I get the following error:

`xcrun error: cannot be used within an App Sandbox.`

Is there a fix or workaround for this?

**Comment by mathieudutour** [comment]
no, Using a command line tool (git) from an app, it needs to be outside a sandbox. I should precise it in the readme.

**Comment by wanghongjun2014** [comment]
i have the problem , too

**Comment by mathieudutour** [comment]
The app in the mac app store is not supported anymore: http://bohemiancoding.tumblr.com/post/134322691555/leaving-the-mac-app-store
