### ISSUE TITLE
Visual diffing a la github

### ISSUE THREAD

**Issue by kav** [mathieudutour/git-sketch-plugin#41]
I really like the github visual diffing UI shown here: https://help.github.com/articles/rendering-and-diffing-images/ Might be an interesting feature to add. I'll try to take a look myself when I have some bandwidth.

**Comment by mathieudutour** [comment]
Hum that's the all point of this plugin. What would you want to add?

**Comment by kav** [comment]
Ah, seeing it in the screenshot now. Might just be a docs update. The pretty diffing seems to be quite a few steps which may be how I missed it.

**Comment by mathieudutour** [comment]
The step is only to commit with the checkbox `generate pretty diffs`.
