### ISSUE TITLE
Two people working on the same file

### ISSUE THREAD

**Issue by edsonespindola** [mathieudutour/git-sketch-plugin#42]
I don't know if I'm doing anything wrong, but I think the way the plugin works today, if another person changes the file I'm working on, when I pull the changes, I can either save mine anyway and overwrite, or revert and lose my changes. 

Are you currently working on a solution for that? 

Would it be possible to, instead of just overwriting the file, add the commit number to the file coming from the remote and keep both? This way I could resolve the conflicts and/or merge them manually. Just a thought. 

Awesome work, btw!

Thanks.

**Comment by mathieudutour** [comment]
No you are right, working on the same file at the same time won't work. I wrote a bit more about it here: https://blog.enki.com/yes-designers-can-use-git-too-79f3cef9c899#.i02htevw5

The only solution would be to reverse engineer the sketch file format to be able to export/import to a text format. That is not something that I want to do, too much work and it will break every time there is a new sketch version. It must come from Bohemian Coding.
