### ISSUE TITLE
delete branch

### ISSUE THREAD

**Issue by ghost** [mathieudutour/git-sketch-plugin#45]
How do you remove a branch from the Checkout branch pull down menu. I have deleted it from Git and it still appears in the menu. Need to remove the Dianna branch.
![screen shot 2016-08-24 at 11 55 32 am](https://cloud.githubusercontent.com/assets/5149601/17943768/afb21b44-69f1-11e6-9de2-3c57bd7ee438.png)

**Comment by ghost** [comment]
Figured it out. Ran this in the command line
git branch -D branch_name

**Comment by mathieudutour** [comment]
Fixed in 0.8.4
