### ISSUE TITLE
bitbucket write to stderr on push

### ISSUE THREAD

**Issue by HYPD** [mathieudutour/git-sketch-plugin#5]
Really loving this tool, but I'm having an issue, that is only kind of an issue - after committing and writing notes, I then hit push and I always receive this error, but the thing is, it actually does push the file. Or it seems to be reflected in the online repo.

![screen shot 2016-02-04 at 12 06 21 pm](https://cloud.githubusercontent.com/assets/970304/12803691/45b48b30-cb38-11e5-8f53-df53ae2f9ebd.png)

ps. the blurred text is the repo and branch url. I'm using bitbucket, but I dont think that makes a difference, does it?

Info: Sketch 3.5.1 w/ latest sketchtool.

**Comment by mathieudutour** [comment]
I actually think it makes a difference. The text showed here is the data going into the err pipe. I've never seen this message when using github or gitlab.

I'll try to test with bitbucket

**Comment by yuanchenhao** [comment]
<img width="532" alt="2016-02-21 22 28 32" src="https://cloud.githubusercontent.com/assets/5696660/13372087/dd74c2b8-dd72-11e5-85db-c9723473becb.png">

I got another kind of "Failed" dialogue.

my working flow is like this(mostly on **master** branch)

> 1.Set up an project on gitlab
> 2.git clone the project to local Mac
> 3.Start a new .sketch file and save it in the git-clone folder and **add file to git**
> 4.After making change I **commit**
> 5.Then I **push** then this dialogue appear.
> 

After this dialogue appear, the push was successful.
But some times the commit will not have effect,sometimes after commit-push the version in the gitlab was one version behind the recent sketch file,how to fix it?

**Comment by mathieudutour** [comment]
probably the same as this: https://github.com/mathieudutour/git-sketch-plugin/issues/13

**Comment by mathieudutour** [comment]
it should be fixed in the new release

**Comment by scrumit** [comment]
I was trying bitbucket too and got an error. 
I went back and re-read the documentation and noticed a mention of Github. 

Might it be an idea to clarify that this plugin will work with Github, Gitlab, Bitbucket and any other git protocol based SCCs that users have tested it with? 

Knowing there's issues about security and access, I suspect there's a need for a smidgen more description. 

Happy to help.

**Comment by mathieudutour** [comment]
@scrumit the GitHub mention in the documentation is just there to give an example. The plugin is just handling git, so any git server should work, including gitlab, bitbucket.

Someone manage to get it to work with bitbucket (https://github.com/mathieudutour/git-sketch-plugin/issues/91). Do you remember the error that you got?
