### ISSUE TITLE
If plugin is installed with sketch toolbox trough an error when committing with diff images

### ISSUE THREAD

**Issue by eduarddotgg** [mathieudutour/git-sketch-plugin#50]
### How did it happen?
1. install plugin with sketch toolbox
2. try to commit with diff images
### Error log

/bin/bash: /Users/someuser/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git: No such file or directory

to fix this error i need manually rename folder.
it would be great not to do that

**Comment by mathieudutour** [comment]
oh yeah I have a fix for that already, will push it soon

**Comment by mathieudutour** [comment]
should be fixed in 0.7.2
