### ISSUE TITLE
tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by aledoo** [mathieudutour/git-sketch-plugin#52]
Hello, I start using your plugin but when I want to init git repo this is happen.

Thanks for the plugin and your time!

![captura de pantalla 2016-09-20 a las 11 54 07](https://cloud.githubusercontent.com/assets/4547672/18665751/f7a7a580-7f28-11e6-9a25-2261f1bb4676.png)

**Comment by mathieudutour** [comment]
hum do you have any scripts on your bash using tput or something? It looks like it's really specific to your bashprofile and your config, I never heard of tput before ^^
