### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by methodik** [mathieudutour/git-sketch-plugin#53]
### How did it happen?
1. ctrol + alt + cmd + C
2. Entered git commit message and checked pretty diff box
3. Press OK and I get error message
### Error log

/bin/bash: /Users/matgriffiths/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git: No such file or directory

```
{}
```

**Comment by mathieudutour** [comment]
I'm pretty sure I fixed that on https://github.com/mathieudutour/git-sketch-plugin/releases/tag/0.7.2

Do you have the latest version installed? If so, I didn't properly fix it. You can work around by going to `/Users/matgriffiths/Library/Application Support/com.bohemiancoding.sketch3/Plugins/` and removint any spaces in the git plugin name

**Comment by methodik** [comment]
Ok thanks, I uninstalled and re-installed it and it worked great again. Thanks for getting back to me so quick.

The devs at the company I work at love that I integrate git into my design workflow. Thanks for bringing it into Sketch - helps us a lot!

**Comment by mathieudutour** [comment]
Awesome! 

Would love to hear your though on https://github.com/mathieudutour/git-sketch-plugin/issues/47 :)
