### ISSUE TITLE
Failed commit – Can't encode character

### ISSUE THREAD

**Issue by ricricucit** [mathieudutour/git-sketch-plugin#54]
### How did it happen?
1. trying to commit (with or without pretty diffs)
### Error log

**Failed..**

```
Traceback (most recent call last):
  File "/Users/ricucit/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/getArtboardNames.py", line 13, in <module>
    print artboard["name"]
UnicodeEncodeError: 'ascii' codec can't encode character u' #\u2265' in position 16: ordinal not in range(128)
```

**Comment by mathieudutour** [comment]
Do you have weird (as in with special character) artboard name?

**Comment by ricricucit** [comment]
I guess so...I have them like `Small Devices ( ≥ 768px )`

**Comment by mathieudutour** [comment]
wait, the error happens even when not doing the pretty diffs?

**Comment by ricricucit** [comment]
It happens in both cases. 
1) commit or 2) commit+pretty diffs
