### ISSUE TITLE
"Init git repo" not asking for the URL of remote

### ISSUE THREAD

**Issue by Joellepeters** [mathieudutour/git-sketch-plugin#57]
Sketch 40.3. 

It created a git repo, but doesn't prompt a popup (?) to add the remote.

**Comment by mathieudutour** [comment]
hum weird, it used to right?

**Comment by Joellepeters** [comment]
@mathieudutour This is my first time experimenting with the plugin. Is there anything obvious I could be missing outside the basic documentation? The plugin is successfully creating branches, allowing me to write commit messages and generated artboard diffs.

**Comment by mathieudutour** [comment]
hum not sure what's happening. I'll try to look into it. You can add the remote manually tho (Git -> Advanced -> Open Terminal and then `git remote add origin URL`)

**Comment by Joellepeters** [comment]
Thanks for responding so quickly. Yeah, I tried manually adding the remote (origin) and pushing a commit via Sketch, but no luck unfortunately. Checked `git log` and realised that committing via Sketch doesn't seem to be working for me either. Will keep playing around.

**Comment by Joellepeters** [comment]
I've managed to resolve issue after uninstalling a bunch of other Sketch plugins.

**Comment by mathieudutour** [comment]
ok, Do you have any idea which of the plugins were conflicting?

**Comment by jasonkylefrank** [comment]
Hi @mathieudutour. I may be having a similar problem to what @Joellepeters ran into.  When I run the `Init Git Repo` command using the plugin, it doesn't seem to actually intialize a Git repo... at least I can't find one and subsequent actions don't seem to work either.

Can you please tell me **where** the initialized Git repo gets created?  That would help me track things down.

I've looked in the directory that my Sketch file is stored in and don't see any Git repo there. Where else should I check?  I didn't see anything in the documentation that explained where it puts it.  Thanks!

**Comment by mathieudutour** [comment]
So it goes into the folder where the opened sketch file is located and init the repo there

**Comment by jasonkylefrank** [comment]
In that case it must be failing.

**Comment by jasonkylefrank** [comment]
I just checked the process on a second file just to be sure nothing strange was going on with the first file.  The second one failed as well.  I checked the directory that the sketch file was in via both Finder and the terminal (ran `ls -a` in the terminal to see all hidden files) but neither shows anything besides the sketch file.  What else can I do to help diagnose the issue?

**Comment by mathieudutour** [comment]
* is the file in a special directory?
* Could you open the terminal through the git polugin (Plugin -> Git -> advanced -> terminal) and type `git init`? What is the output?

**Comment by jasonkylefrank** [comment]
(1) The file is not in any special directory
(2) I got an error.  Looks like I probably have something screwed up on my machine.  The error was:
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

I'll work on fixing that and try the plugin again once that's resolved.  Sorry for the false alarm.  My bad.  :-)

**Comment by mathieudutour** [comment]
No worries. It's probably something that the plugin should handle, showing this error instead of failing silently

**Comment by mathieudutour** [comment]
it should be fix with 0.8.2
