### ISSUE TITLE
More lines for Commit

### ISSUE THREAD

**Issue by michaelkodim** [mathieudutour/git-sketch-plugin#58]
Hello!
It would be great to have the Commit Field as an area with multiple lines. This would give one the opportunity to write a more detailed commmit, structured in a shot summary in the first line and details in the further paragraphs ... 

I think this would be a cool improvement, especially for bigger teams that need to collaborate a lot.

What do you think? Is this possible?

**Comment by mathieudutour** [comment]
yes that's a good idea!

**Comment by michaelkodim** [comment]
works great, thanks!
