### ISSUE TITLE
Error trying to commit /bin/bash: shell_session_update: command not found

### ISSUE THREAD

**Issue by iamlasse** [mathieudutour/git-sketch-plugin#61]
### How did it happen?
1. Started new file
2. Saved
3. Issued git commit command

### Error log
```
{/bin/bash: shell_session_update: command not found}
```

**Comment by mathieudutour** [comment]
Are you using RMV by any chance?

**Comment by mathieudutour** [comment]
it might be fixed in the new release, could you try?

**Comment by yanfeng42** [comment]
I was having this issue and  **rvm get head** fixed it . Thanks https://github.com/direnv/direnv/issues/210#issuecomment-236032558

Confirm, it works!
