### ISSUE TITLE
pretty diffs for Sketch symbols

### ISSUE THREAD

**Issue by jasonkylefrank** [mathieudutour/git-sketch-plugin#62]
Our team is primarily interested in using Git as a repository of Sketch **symbols**.  Right now it appears that your plugin generates png images of regular artboards but not *symbol* artboards.  Is there a way to tell it to generate the png images of the symbol artboards?
#question

**Comment by mathieudutour** [comment]
oh that's a good question. I don't have the answer, I'll have to look into it

**Comment by mathieudutour** [comment]
I have completely rewritten the plugin in the new release, as well as generating pretty diffs for symbols.

I might have introduced some bugs because of the rewrite (hopefully not) but the iterations will be easier now

**Comment by bryanberger** [comment]
@mathieudutour I recommend that this should be added as a User Preference.

**Example:**
I have a Sketch doc with hundreds of symbols, that I don't require diffing for. Since `sketchtool` blocks the UI until its finished, every commit `beach-balls` for 10-15 seconds and there is currently no way within the plugin preferences to disable that.

**Comment by mathieudutour** [comment]
you can ignore pages for the export: https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/sketchignore.md (this is a nicer solution because you can add the `.sketchignore` file to git so that everybody ignores it)

**Comment by mathieudutour** [comment]
I actually think that the entire config concerning the export (folder, scale, etc.) should be in a file that you commit to the repo as well. Then yes, it would make sense to have a option to disable the symbols export (#69)

**Comment by jasonkylefrank** [comment]
As I mentioned in the other thread, the new Symbol export seems to be working well.  Thought I'd provide some brief feedback.

First, I **love** how it creates the Symbol hierarchy via folders:

![image](https://cloud.githubusercontent.com/assets/7502365/20728398/8b70ac36-b64b-11e6-9d24-07b9538fec0e.png)

Regarding hierarchy in general though, we would like it if the plugin put would create folders corresponding to the Sketch **pages** as well.  Then we'd have a folder for `Symbols`, as well as other pages like `Overview screen`, `Details screen`, etc.
