### ISSUE TITLE
Git.sketchplugin is not installing the plugin

### ISSUE THREAD

**Issue by jcao02** [mathieudutour/git-sketch-plugin#65]
In release 0.8.1, double clicking Git.sketchplugin is not installing the plugin (it does nothing actually). Tried to downgrade the version to 0.7.4 but it crashes sketch:

![screen shot 2016-11-25 at 10 40 34](https://cloud.githubusercontent.com/assets/2745307/20629946/982208f2-b304-11e6-8004-0c15c2333619.png)

**Sketch version**: 41.1

**Comment by mathieudutour** [comment]
oops sorry, should be fine with: https://github.com/mathieudutour/git-sketch-plugin/releases/download/0.8.1/Git.sketchplugin.zip

**Comment by jcao02** [comment]
@mathieudutour it's working now! Thank you
