### ISSUE TITLE
Plugin crashes Sketch upon opening any file after the new Sketch 41.2 update 

### ISSUE THREAD

**Issue by jasonkylefrank** [mathieudutour/git-sketch-plugin#66]
Hello!

I just upgraded Sketch to v41.2.  Now Sketch crashes every time I open any file (even a new file).  Sketch claimed that they believe it was due to some plugins, so I diagnosed the issue by disabling all my Sketch plugins and then one-by-one reenabling them until the crashing started again.

When I reenabled this Git-Sketch-Plugin the crashing resumed.  I also reconfirmed this issue by enabling **only** this plugin (no other plugins enabled), with the same result.

I tried updating this plugin to the latest version that you just release, but that crashes Sketch as well.  The version of this plugin that I have installed is v0.7.4, and when I double-click on the Git.sketchplugin file for your newest version it immediately crashes Sketch (if it is open) and does not upgrade the plugin.  If I try double-clicking on the file when Sketch is not open, it just fails silently.

Thanks for reading and let me know if you have questions.

**Comment by mathieudutour** [comment]
hum I can't repro. Is there any errors when it crashes?

**Comment by jackmakesthings** [comment]
I'm also seeing this, immediately after updating Sketch to 41.2. The app opens to the welcome screen, but trying to open or create a file causes it to crash. I found these messages logged in the OS console after the crash:
```
Sketch[8176]: Exception: TypeError: null is not an object (evaluating 'res.version')
```
```
update (Sketch Plugin)[8176]: TypeError: null is not an object (evaluating 'res.version')
line: 34
sourceURL: /Users/jgold/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git Sketch Plugin/Git.sketchplugin/Contents/Sketch/update.cocoascript
column: 14
stack: getNewestVersionNumber@/Users/jgold/Library/Application 
Support/com.bohemiancoding.sketch3/Plugins/Git Sketch 
Plugin/Git.sketchplugin/Contents/Sketch/update.cocoascript:34:14
onOpenDocument@/Users/jgold/Library/Application 
Support/com.bohemiancoding.sketch3/Plugins/Git Sketch 
Plugin/Git.sketchplugin/Contents/Sketch/update.cocoascript:80:45
```

This is on a Macbook Pro running 10.11.6.

**Comment by mathieudutour** [comment]
hum that's weird... I updated the zip: https://github.com/mathieudutour/git-sketch-plugin/releases/download/0.8.1/Git.sketchplugin.zip. Could you try and tell me if it fixes the issue

**Comment by jasonkylefrank** [comment]
I think your new v0.8.2 fixed it!

Also just got to quickly test out your new Symbols png generation and such and that seems to be working as well!  I have some feedback about that and will report that in the other thread dedicated to that topic.  Thanks for the fix!!

**Comment by jdsimcoe** [comment]
@mathieudutour @jasonkylefrank `0.8.1` fixed it for me, thanks!

**Comment by pklada** [comment]
0.8.2 fixes it. Thanks!

**Comment by jdsimcoe** [comment]
@pklada I don't see any `0.8.2` here: https://github.com/mathieudutour/git-sketch-plugin/releases

**Comment by pklada** [comment]
Doesnt appear to be an official release yet, but: https://github.com/mathieudutour/git-sketch-plugin/commit/7eeab0070460df4977753a3d5c195636acfd0130

**Comment by mathieudutour** [comment]
just realeased 0.8.2
