### ISSUE TITLE
Plugin Won't install Sketch 41.2

### ISSUE THREAD

**Issue by cfinefield** [mathieudutour/git-sketch-plugin#68]
Having an issue where the plugin won't install.

**Comment by jjcall** [comment]
Same issue for me. Install and plugin does not show up.

**Comment by yuchuanxi** [comment]
Same issue for me. tag 0.8.1

and tag 0.8.0 is OK

**Comment by mathieudutour** [comment]
I updated the zip: https://github.com/mathieudutour/git-sketch-plugin/releases/download/0.8.1/Git.sketchplugin.zip. Could you try and tell me if it fixes the issue?

**Comment by bryanberger** [comment]
Zip works fine. Installing it via [Sketch Toolbox](http://sketchtoolbox.com/) doesn't work

**Comment by mathieudutour** [comment]
hum... I'm not sure how Sketch Toolbox works and it seems to be abandoned...

**Comment by cfinefield** [comment]
@mathieudutour The new .zip worked! I had to manually remove the old plugin from ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins. Thanks!
