### ISSUE TITLE
Not working with 3.5.1

### ISSUE THREAD

**Issue by hfactor** [mathieudutour/git-sketch-plugin#7]
While init git repo, it's showing an error with message : 
{ column = 25; line = 11; sourceURL = "/Users/USER/Library/Application Support/com.bohemiancoding.sketch3/Plugins/CSSketch-master/git-sketch-plugin-master/Git.sketchplugin/Contents/Sketch/Init.cocoascript"; }

**Comment by mathieudutour** [comment]
Any particular reason why git-sketch-plugin-master is inside CSSketch-master?
I can't reproduce. Could you open the Console app and see the entire error message (there should be an extra field in the error object which doesn't show in the alert)?

**Comment by hfactor** [comment]
Looks like it was some mistakes from my side. Working fine now.
