### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by florentmorin** [mathieudutour/git-sketch-plugin#72]
Hello,

I can't install plugin.

Configuration:
- Sketch 41.2 (35397)
- macOS Sierra 10.12.1 (16B2555)
- git 2.10.1

Tests:
- double-click on Git.sketchplugin
- drag'n'drop Git.sketchplugin to Plugins folder.

Thanks!

**Comment by florentmorin** [comment]
In console, I have this message:
"Missing plugin manifest.json"

So, I compile it from source code.
And now, it works fine.

**Comment by mathieudutour** [comment]
Yes, because the plugin needs to be compiled, you need to download it from the releases: https://github.com/mathieudutour/git-sketch-plugin/releases if you don't want to compile it yourself

**Comment by dollysartwork** [comment]
Cannot install Git.sketchplugin (git-sketch-plugin-0.11.2) on Sketch 46.2 (macOS Sierra 10.12.6)
