### ISSUE TITLE
ReferenceError: Can't find variable: image v0.8.3

### ISSUE THREAD

**Issue by bryanberger** [mathieudutour/git-sketch-plugin#75]
### How did it happen?
1. Git > Advanced > Export sketch file to JSON

### Error log

```
ReferenceError: Can't find variable: image
{
	"line": 258,
	"column": 27
}
```

**Comment by mathieudutour** [comment]
Oh that's still very work in progress ;) Do you have a sketch file example that I could use to test as many sketch features as possible?

**Comment by mathieudutour** [comment]
should be fixed here though: https://github.com/mathieudutour/git-sketch-plugin/files/646700/Git.sketchplugin.zip

**Comment by jdsimcoe** [comment]
@mathieudutour Just downloaded this and committing is broken. JSON export broken. JSON import throws error too. :(

**Comment by mathieudutour** [comment]
Erf, what did I mess up... I'll look at it in a bit
