### ISSUE TITLE
I had installed git-sketch plugin, but it's doesn't work

### ISSUE THREAD

**Issue by YoshiLiao** [mathieudutour/git-sketch-plugin#77]
hi Mathieu Dutour

Thank you for all you have done

but when I want try to use the git-sketch

there's something wrong.

I had installed sketch-git plugin

In the sketch Plugins folder

I can see sketch-git plugins, like image

![image](https://cloud.githubusercontent.com/assets/16816058/21545474/0918f0d8-ce13-11e6-8681-ee9eac0d2c81.png)

but in the Toolbar→Plugins

I can't see the sketch-plugins

![image](https://cloud.githubusercontent.com/assets/16816058/21545531/793e26ee-ce13-11e6-9fa4-e27cc3039e08.png)

I had installed the plugins so much time

but it's doesn't work

can you help me to solve the problem

ps：my sketch edition：Version 41.2

thanks a lot

**Comment by mathieudutour** [comment]
How did you install it? You need to download the zip here: https://github.com/mathieudutour/git-sketch-plugin/releases/latest

**Comment by jdsimcoe** [comment]
@YoshiLiao Also just double click the `.sketchplugin` file and don't try dragging the folder to the `/Plugins` directory.

**Comment by YoshiLiao** [comment]
Thanks Mathieu and jdsimcoe

Initially, I installed git-sketch plugin from the page below：(with double click the 「.sketchplugin」)

![image](https://cloud.githubusercontent.com/assets/16816058/21557682/dd8518fe-ce6a-11e6-853d-392ebfc977b4.png)

It's can't be a correct installation

when I use the link Mathieu provided below, It work

https://github.com/mathieudutour/git-sketch-plugin/releases/tag/v0.8.3

I don't know the difference of plugins between two downloads

but I think the problem has solved 

thank you for understanding of my poor English

Thank you again for everything you’ve done...

**Comment by mathieudutour** [comment]
Oh I didn't change the landing page. Thanks for reporting

**Comment by mathieudutour** [comment]
Fixed
