### ISSUE TITLE
Installation failed:Missing plugin manifest.json:v0.8.4

### ISSUE THREAD

**Issue by asuyakono** [mathieudutour/git-sketch-plugin#79]
After Installation, I couldn't  find "Plugins > Git".

So I checked log which include this message:

```
Missing plugin manifest.json at URL: file:///Users/[username]/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/Contents/Sketch/manifest.json «Plugin Developer»
```

FYI, I installed "v0.8.3" without any problem.

sketch.app: 41.2 (35397)
git.sketchplugin: v0.8.4

**Comment by mathieudutour** [comment]
oops, there `.zip` was missing at the end of the file. Should be fixed now: https://github.com/mathieudutour/git-sketch-plugin/releases/download/v0.8.4/Git.sketchplugin.zip
