### ISSUE TITLE
Suggestion: Add minimal how-to in README for git lfs

### ISSUE THREAD

**Issue by loklaan** [mathieudutour/git-sketch-plugin#8]
When available, `.png` and `.sketch` should be tracked by [git lfs](https://git-lfs.github.com/).

This should be as easy as doing the following steps:
1. Install git lfs onto your system
2. `git lfs install` inside of your repo
3. `git lfs track "*.png"` & `git lfs track "*.sketch"` inside of your repo

It should also be noted that your remote needs to have git lfs support.

This info is by no means critical to using this plugin, but it aids in maintaining a healthy git repo.

**Comment by mathieudutour** [comment]
Good idea! Do you want to create a PR?

**Comment by loklaan** [comment]
Yeah sure - I put this up with the intention to test on the same day but I couldn't get around to it.

Expect a PR soon. :soon: :smile_cat:

**Comment by loklaan** [comment]
Closing this in favor of #10.
