### ISSUE TITLE
Plugin doesn't install on macOS 10.12.2 Sketch version 41.2

### ISSUE THREAD

**Issue by michaelmov** [mathieudutour/git-sketch-plugin#80]
Double clicking on Git.sketchplugin opens Sketch, but doesn't install the plugin.

**Comment by mathieudutour** [comment]
did you download the plugin from here: https://github.com/mathieudutour/git-sketch-plugin/releases/tag/v0.8.4 ?

**Comment by michaelmov** [comment]
Ah! Looks like I was downloading from the source. Downloading from the provided link works. Thank you!

**Comment by drasnop** [comment]
@mathieudutour The download link provided on https://mathieudutour.github.io/git-sketch-plugin/ points to the wrong download location (https://github.com/mathieudutour/git-sketch-plugin/zipball/master) instead of https://github.com/mathieudutour/git-sketch-plugin/releases/latest

**Comment by mathieudutour** [comment]
Indeed, forgot to change the big button link. Thanks
