### ISSUE TITLE
Can't init git repo

### ISSUE THREAD

**Issue by JoeAllison** [mathieudutour/git-sketch-plugin#83]
When installing the plugin and clicking 'init git repo' I'm getting the following error message:
![image](https://cloud.githubusercontent.com/assets/3280156/21999611/ed75706c-dc32-11e6-8348-fa6ec6a9f88d.png)

Is this a known issue, and do you know how I can get around it?

**Comment by mathieudutour** [comment]
I'm guessing you need to install the xcode command line tools.
Can you open your terminal and run `xcode-select --install`? 

If it fixes the issue, I'll update the README and add it to the requirements

**Comment by JoeAllison** [comment]
Thanks for your help :) this worked although when I try and set up a new repository on github and try to add it using 'init git repo', I get this message. Am I doing something wrong here, or is there a fix for this? I also noticed that 'Plugins > Git > New branch' that's mentioned in the getting started guide isn't accessible through the menu.
![image](https://cloud.githubusercontent.com/assets/3280156/22014335/18cf56c6-dc95-11e6-95ee-a5d8c81966bf.png)

**Comment by mathieudutour** [comment]
Looks like the repo is already initialised. You can check it by opening the terminal (Plugins -> Git -> Advanced -> Terminal) and type `git remote`. It will list the remotes. You can then type `git remote get-url MY_REMOTE` (where MY_REMOTE will probably be `origin`) and check that the url correspond to your repository.

Good point for the `Plugins > Git > New branch`, it is now under `Plugins > Git > Branches`. I will update the README

**Comment by JoeAllison** [comment]
Thanks, I found the Plugins -> Git -> Advanced -> Terminal didn't open the terminal, but I accessed it manually and found I needed to set it up again because i'd set the repo up in the wrong place at first.

I then set it up with a new repository on github, but when I try to make the first push after committing, I get this error about not being able to read the username from github:
![image](https://cloud.githubusercontent.com/assets/3280156/22017239/721f3cf8-dca1-11e6-9a05-2ad4a76fa584.png)

**Comment by mathieudutour** [comment]
Ahah I think you are hitting every pain points. Look at the 2 links at the bottom this doc: https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/getting-started.md. You will only need to do that once.

**Comment by JoeAllison** [comment]
Thanks, I ran those steps to add the username and email and clear the cache, but it's still showing the same error. It's showing this error when I make a commit now: 
![image](https://cloud.githubusercontent.com/assets/3280156/22023292/7a9e3c8c-dcbd-11e6-905c-6e82e6d0c8b7.png)

**Comment by afaye0211** [comment]
hi I got same issue also. 
I've done "Set Up Git" and "Caching your GitHub password in Git" but still got this error
while doing "PULL".

Error Message

<img width="532" alt="screen shot 2017-01-19 at 11 26 10" src="https://cloud.githubusercontent.com/assets/25215217/22092672/77f08584-de3a-11e6-83c6-27b59408e689.png">

**Comment by mathieudutour** [comment]
@JoeAllison Hum, not sure what's happening here, let's try to debug. 
- What happens if you only generate the diffs (Git -> Advanced -> Generate pretty diffs)?
- What happens if you try to push?
- What happens if you try to commit without generating the pretty diffs?

@afaye0211 Well it seems that "caching your password" didn't work. Can you try to open the terminal (Git -> Advanced -> Terminal) and type `git pull`?

**Comment by Belindachenhj** [comment]
I have the same issue here.

1. If I only generate the diffs (Git -> Advanced -> Generate pretty diffs), then shows Artboards Exported. 

<img width="246" alt="2017-03-03 12 44 40" src="https://cloud.githubusercontent.com/assets/25971363/23538574/39a5d80a-000f-11e7-979f-0b94e6105373.png">

2. If I try to push,
<img width="445" alt="2017-03-03 12 46 02" src="https://cloud.githubusercontent.com/assets/25971363/23538597/6421f028-000f-11e7-99a9-7540df05a6f1.png">

3. If I try to commit without generating the pretty diffs,
<img width="873" alt="2017-03-03 12 46 53 1" src="https://cloud.githubusercontent.com/assets/25971363/23538613/85957d38-000f-11e7-8cc8-1cb043fe83e1.png">

But I still cant push.

**Comment by mathieudutour** [comment]
@Belindachenhj Look at the 2 links at the bottom this doc: https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/getting-started.md. You will only need to do that once.

**Comment by Belindachenhj** [comment]
@mathieudutour  Thank you for reply.

I set up then push again, but still can't.

<img width="439" alt="2017-03-06 2 26 09" src="https://cloud.githubusercontent.com/assets/25971363/23598969/f86807a2-0278-11e7-953f-44e9e3edb2bd.png">

I think maybe I have to pay for the LFS ?

**Comment by mathieudutour** [comment]
so either the repo doesn't exist on github or it's private and you don't have access to it
