### ISSUE TITLE
Export main artboards only

### ISSUE THREAD

**Issue by melaridi** [mathieudutour/git-sketch-plugin#86]
Hi @mathieudutour! 

Thank you for this amazing plugin. It is very helpful. Is there a way it could export the main Artboards panel and exclude styles and symbols?

In my case, I want to export Errata page artboards only.

![screenshot 2017-01-24 13 39 14](https://cloud.githubusercontent.com/assets/12257565/22263735/0cb35972-e23b-11e6-93d7-9c36bfe56cd6.png)

Thanks again!

**Comment by mathieudutour** [comment]
Have you tried to look at this: https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/sketchignore.md ? I'm not sure if it works with symbols though

**Comment by melaridi** [comment]
Awesome! I'll give that a shot in a bit :) Thanks!
