### ISSUE TITLE
No way to merge sketch files

### ISSUE THREAD

**Issue by vinceangeloni** [mathieudutour/git-sketch-plugin#87]
This might not be clear enough, or maybe I am doing something wrong. 

Situation:
- I make changes to my `ui.sketch` file. My co-worker makes changes to his `ui.sketch` file.
- I stash my changes into a new branch, no biggie.
- My co-worker commits, I pull in his changes.
- I want to put merge my branch with my previous `ui.sketch` changes into the now updated master with his changes.

`ui.sketch` is now a conflict with no way to resolve. I understand merging these files probably isn't possible.

Am I correct?

**Comment by mathieudutour** [comment]
Indeed, I wrote a bit more about it here: https://blog.enki.com/yes-designers-can-use-git-too-79f3cef9c899#.hkpap1dsi

I'm currently working on a way to enable merge but it's very WIP and I don't have much time those days: https://github.com/mathieudutour/git-sketch-plugin/pull/74
