### ISSUE TITLE
v0.90 isn't running after being installed on Sketch 42

### ISSUE THREAD

**Issue by andyhugelier** [mathieudutour/git-sketch-plugin#88]
I'm running Sketch 42, installed the latest version 0.90, and the plugin doesn't show in the menu, even though it appears to have installed into the correct directory. I've restarted Sketch and my computer, uninstalled the previous plugin and reinstalled everything fresh and still can't get it to work. FWIW Clicking on the installer doesn't produce a confirmation that it was installed either. 

I also reinstalled other plugins without issue to be sure it was specifically related to this one.

Any idea what is going on?

**Comment by mathieudutour** [comment]
Is it related to this: https://github.com/mathieudutour/git-sketch-plugin/issues/80 ?

**Comment by alexeiboronnikov** [comment]
Same here, can't see the plugin in 42

**Comment by mathieudutour** [comment]
Can you confirm that you installed the plugin by downloading it from the releases page https://github.com/mathieudutour/git-sketch-plugin/releases?

**Comment by alexeiboronnikov** [comment]
@mathieudutour many thanks mate! the one from the releases page works fine

**Comment by andyhugelier** [comment]
This worked for me as well. Thanks!
