### ISSUE TITLE
Plugin can't be installed

### ISSUE THREAD

**Issue by mrowdy** [mathieudutour/git-sketch-plugin#90]
When i doubleclick the Git.sketchplugin file, Sketch opens immediately but the plugin isn't added. 

When i copy Git.sketchplugin into the plugin directory of sketch, it won't show up in sketch.

Other Plugins work fine. I tried installing and uninstalling several other plugins.
Reproducible on my other mac. 

Sketch version: 24

**Comment by mathieudutour** [comment]
https://github.com/mathieudutour/git-sketch-plugin/blob/master/docs/FAQ.md#i-installed-the-plugin-but-its-not-showing-in-the-sketch-plugin-menu
