### ISSUE TITLE
Bitbucket support?

### ISSUE THREAD

**Issue by ziyafenn** [mathieudutour/git-sketch-plugin#91]
I was curious if it's possible to integrate that plugin into Atlassians bitbucket? Thanks

**Comment by mathieudutour** [comment]
Probably, there is no "github" hardcoded in the plugin. I don't know if bitbucket shows diffs for images though.

**Comment by jkbz** [comment]
We are using Stash/Bitbucket at my company and the plugin works for us. We've seen some errors but I'm not entirely sure we are setting things up properly.

**Comment by mathieudutour** [comment]
Cool! I'm closing this issue then. @hkbz feel free to report any errors you see, we could fix them ;)

**Comment by ziyafenn** [comment]
@jkbz @mathieudutour  Guys, can you help me to figure out how to use this plugin with bitbucket? I have no idea :(

**Comment by jkbz** [comment]
@ziyafenn - Can you provide some details on the issue you are having? For instance I'm assuming you have:

1 - Installed git (if needed)
2 - Cloned or created the repository with your files
3 - Installed the Sketch plugin

Screenshots would be helpful
