### ISSUE TITLE
Can't save preferences

### ISSUE THREAD

**Issue by davidrpoliti** [mathieudutour/git-sketch-plugin#92]
Preferences aren't saved. Making changes and clicking purple Save button doesn't save nor close modal.
![screenshot 2017-02-10 09 48 55](https://cloud.githubusercontent.com/assets/4054043/22837588/25483578-ef76-11e6-8c2a-b12f82b550b4.png)

**Comment by mathieudutour** [comment]
Thanks for the bug report. Should be fixed in 0.9.1

**Comment by davidrpoliti** [comment]
Thank you, sir!
