### ISSUE TITLE
A note about the use of GPG signed commits

### ISSUE THREAD

**Issue by willdurand** [mathieudutour/git-sketch-plugin#93]
**Edit:** while filling this issue about a potential bug, I tried to investigate to give more hints about the bug I wanted to report. I discovered that VSCode had pretty much the same bug report, cf. https://github.com/Microsoft/vscode/issues/5065. I think it would be nice to add an entry to the FAQ maybe. I created this issue for documentation purpose anyway. Let me know if I can help on something.

## TL;DR

If you get an error about `tty` and you do sign your commits, tell GPG not to use `tty`:

    $ echo 'no-tty' >> ~/.gnupg/gpg.conf

Below is my original bug report:

---

Hi there!

Thanks for your great plugin, I cannot really use it (yet) but it looks very interesting so far!

### How did it happen?
1. Created a git repo (init) within Sketch (using the plugin)
2. Added the current sketch file using the plugin
3. Tried to commit with the plugin (did not check the input to generate pretty diffs)
4. 💥 

My git configuration is set to sign all my commits (cf. https://help.github.com/articles/telling-git-about-your-gpg-key/). **Edit:** For more information, see: https://github.com/Microsoft/vscode/issues/5065.

### Error log

<img width="532" alt="screen shot 2017-02-11 at 22 50 30" src="https://cloud.githubusercontent.com/assets/217628/22857790/8a3fc784-f0ac-11e6-9e27-c6c72e127818.png">

**Comment by mathieudutour** [comment]
Good to know thanks! Do you want to create PR with an entry in the FAQ?

**Comment by willdurand** [comment]
Sure, I can do that!
