### ISSUE TITLE
Error initiating new repo - "fatal: could not read Password..."

### ISSUE THREAD

**Issue by jkbz** [mathieudutour/git-sketch-plugin#95]
I am setting up a new repository and I received an error when clicking PULL from the plugin menu:

"fatal: could not read Password for 'https://username@server.company.com': Device not configured"

I initiated the repo via Terminal and I was attempting to commit/push the first file from Sketch. There was an error (not sure what) so instead I chose "init repo" from the plugin menu. I pasted the URL:

https://username@server.company.com/folder/repo_name.git

I attempted to do a pull, received the error. 

Most of my git work has been via Sourcetree or Terminal, so it's possible that I screwed the setup up or something. 

![2017-02-13 at 4 41 08 pm_censored](https://cloud.githubusercontent.com/assets/6930301/22904975/6fe48d6e-f20c-11e6-8ef2-6dc1b165fe6a.jpg)

**Comment by jkbz** [comment]
So I did "git pull" from terminal and it asked for my password. Not sure why it isn't using my SSH key, but maybe we could modify the plugin to prompt for password?

**Comment by mathieudutour** [comment]
Hum we potentially could prompt for the password but we would need to ask it every time as I don't really want to store it. Or maybe we could configure git to remember the password https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by jkbz** [comment]
I would definitely recommend saving the password in the Keychain. Terminal and SourceTree both do this, so it is standard behavior.

**Comment by 0xcaff** [comment]
One way you could get around this is by generating the files for pretty-diffs (Plugins > Git > Advanced > Generate files for pretty diffs) and committing with source tree or your tool of choice.

If you want to use the password from the keychain, checkout the solution in #132.

**Comment by 0xcaff** [comment]
I believe this is solved. If it is not, please re-open.
