### ISSUE TITLE
Error on commit attempt. Possible failure to enter password?

### ISSUE THREAD

**Issue by rebdev** [mathieudutour/git-sketch-plugin#98]
### How did it happen?
1. Went Plugins -> Git -> Commit
2. Added a comment.
3. Ticked the 'pretty diffs' box
4. Got 'Failed.... Unknow error' error.

I've added the repo (this I can say for certain because on trying to add it a second time it informed me so) but I haven't entered a password anywhere. Maybe that's causing the problem? Where do enter my password?

### Error log

```
{}
```

**Comment by 0xcaff** [comment]
Duplicate of #95
